<?php
session_start();
require_once('config.php');
require_once('TCPDF-main/tcpdf.php');

// Error reporting (remove in production)
error_reporting(0);

// Redirect to login if not logged in
if (!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit();
}

// Get order ID from URL
$order_id = isset($_GET['order_id']) ? sanitizeInput($_GET['order_id']) : null;

if (!$order_id) {
    die("Order ID is required");
}

// Custom PDF class with proper header handling
class MYPDF extends TCPDF {
    protected $order_id;
    
    public function __construct($orientation='L', $unit='mm', $format='A4', $unicode=true, $encoding='UTF-8', $diskcache=false, $pdfa=false) {
        parent::__construct($orientation, $unit, $format, $unicode, $encoding, $diskcache, $pdfa);
        $this->cellspacing = 0;
    }
    
    public function setOrderId($order_id) {
        $this->order_id = $order_id;
    }
    
    // Page header
    public function Header() {
        $this->SetFont('helvetica', 'B', 12);
        $this->Cell(0, 10, 'JOB CARD REPORT - ORDER ID: '.$this->order_id, 0, false, 'C', 0, '', 0, false, 'M', 'M');
        $this->Ln(10);
    }
    
    // Page footer
    public function Footer() {
        $this->SetY(-15);
        $this->SetFont('helvetica', 'I', 8);
        $this->Cell(0, 10, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
    }
}

// Create PDF document
$pdf = new MYPDF('L', PDF_UNIT, 'A4', true, 'UTF-8', false);
$pdf->setOrderId($order_id);

// Set document information
$pdf->SetCreator('Job Route System');
$pdf->SetAuthor($_SESSION['full_name']);
$pdf->SetTitle('Job Card Report - ' . $order_id);
$pdf->SetSubject('Job Card with Operations Data');

// Set margins
$pdf->SetMargins(10, 20, 10);
$pdf->SetHeaderMargin(10);
$pdf->SetFooterMargin(15);
$pdf->SetAutoPageBreak(TRUE, 25);

// Add a page
$pdf->AddPage();

// Set colors
$headerColor = array(5, 63, 92);    // Dark blue
$headerColor2 = array(24, 83, 112);    // Dark blue
$primaryColor = array(41, 128, 185); // Blue
$rowColor1 = array(255, 255, 255);   // White
$rowColor2 = array(240, 248, 255);   // Alice blue

// Main title
$pdf->SetFont('helvetica', 'B', 16);
$pdf->SetTextColor($headerColor[0], $headerColor[1], $headerColor[2]);
$pdf->Cell(0, 10, 'JOB CARD DETAILED REPORT', 0, 1, 'C');
$pdf->SetFont('helvetica', '', 9);
$pdf->Cell(0, 5, 'Generated By: '.$_SESSION['full_name'].' | Date: '.date('d-m-Y H:i:s'), 0, 1, 'R');
$pdf->Ln(8);

// Get job card data
$sql = "SELECT * FROM job_cards WHERE order_id = '$order_id'";
$result = $conn->query($sql);

if ($result->num_rows == 0) {
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->Cell(0, 10, 'No job card found with Order ID: ' . $order_id, 0, 1, 'C');
    $pdf->Output('job_card_report_' . $order_id . '.pdf', 'D');
    exit();
}

$job = $result->fetch_assoc();
$job_id = $job['id'];

// Job Card Information Table
$pdf->SetFont('helvetica', 'B', 12);
$pdf->SetFillColor($headerColor[0], $headerColor[1], $headerColor[2]);
$pdf->SetTextColor(255, 255, 255);
$pdf->Cell(0, 8, 'JOB CARD INFORMATION', 0, 1, 'C', true);
$pdf->SetTextColor(0, 0, 0);

$html = '<style>
    .table-border { border-collapse: collapse; width: 100%; margin-bottom: 10px; }
    .table-border th { padding: 6px; text-align: center; background-color: rgb('.$headerColor2[0].','.$headerColor2[1].','.$headerColor2[2].'); color: white; font-weight: ; font-family: "Times New Roman", Times, serif; border: 0.5px solid #000; }
    .table-border td { padding: 5px; text-align: center; border: 0.5px solid #ddd; }
    .even-row { background-color: rgb('.$rowColor2[0].','.$rowColor2[1].','.$rowColor2[2].'); }
    .odd-row { background-color: rgb('.$rowColor1[0].','.$rowColor1[1].','.$rowColor1[2].'); }
</style>

<table class="table-border">
    <tr>
        <th width="15%">Order ID</th>
        <th width="15%">Product Model</th>
        <th width="20%">Customer</th>
        <th width="10%">Quantity</th>
        <th width="10%">Status</th>
        <th width="15%">PO Number</th>
        <th width="15%">Created By</th>
    </tr>
    <tr class="odd-row">
        <td>'.$job['order_id'].'</td>
        <td>'.$job['product_model'].'</td>
        <td>'.$job['customer_name'].'</td>
        <td>'.$job['quantity_produced'].'</td>
        <td><b>'.strtoupper($job['status']).'</b></td>
        <td>'.$job['po_number'].'</td>
        <td>'.$job['created_by'].'</td>
    </tr>
</table>

<table class="table-border">
    <tr>
        <th width="33%">Start Date</th>
        <th width="33%">Target Date</th>
        <th width="33%">PO Date</th>
       
    </tr>
    <tr class="even-row">
        <td>'.date('d-m-Y', strtotime($job['start_date'])).'</td>
        <td>'.date('d-m-Y', strtotime($job['target_date'])).'</td>
        <td>'.date('d-m-Y', strtotime($job['po_date'])).'</td>
        
    </tr>
</table>';

$pdf->writeHTML($html, true, false, true, false, '');
$pdf->Ln(10);

// Product Description
$pdf->SetFont('helvetica', 'B', 12);
$pdf->SetFillColor($headerColor[0], $headerColor[1], $headerColor[2]);
$pdf->SetTextColor(255, 255, 255);
$pdf->Cell(0, 8, 'PRODUCT DESCRIPTION', 0, 1, 'C', true);
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('helvetica', '', 10);
$pdf->MultiCell(0, 8, $job['product_desc'], 1, 'L');
$pdf->Ln(12);

// Operations Data
$pdf->SetFont('helvetica', 'B', 12);
$pdf->SetFillColor($headerColor[0], $headerColor[1], $headerColor[2]);
$pdf->SetTextColor(255, 255, 255);
$pdf->Cell(0, 8, 'OPERATIONS DETAILS', 0, 1, 'C', true);
$pdf->SetTextColor(0, 0, 0);

$ops_sql = "SELECT * FROM operations WHERE job_card_id = $job_id ORDER BY operation_no";
$ops_result = $conn->query($ops_sql);

if ($ops_result->num_rows > 0) {
    // Start operations table
    $html = '<style>
        .ops-table { border-collapse: collapse; width: 100%; margin-bottom: 5px; }
        .ops-table th { padding: 6px; text-align: center; background-color: rgb('.$headerColor2[0].','.$headerColor2[1].','.$headerColor2[2].'); color: white; font-weight: ; font-family: "Times New Roman", Times, serif; border: 0.5px solid #000; }
        .ops-table td { padding: 5px; text-align: center; border: 0.5px solid #ddd; }
        .ops-even { background-color: rgb('.$rowColor2[0].','.$rowColor2[1].','.$rowColor2[2].'); }
        .ops-odd { background-color: rgb('.$rowColor1[0].','.$rowColor1[1].','.$rowColor1[2].'); }
    </style>
    <table class="ops-table">
        <tr>
            <th width="10%">Date</th>
            <th width="6%">Op No</th>
            <th width="18%">Operation</th>
            <th width="9%">Produced</th>
            <th width="8%">OK</th>
            <th width="8%">Accepted</th>
            <th width="8%">Rework</th>
            <th width="8%">Rejected</th>
            <th width="15%">Remark</th>
            <th width="10%">Checked By</th>
        </tr>';
    
    $row_count = 0;
    $first_page = true;
    
    while ($op = $ops_result->fetch_assoc()) {
        $row_class = ($row_count % 2) ? 'ops-even' : 'ops-odd';
        
        $html .= '<tr class="'.$row_class.'">
            <td>'.date('d-m-Y H:i:s', strtotime($op['operation_date'])).'</td>
            <td>'.$op['operation_no'].'</td>
            <td>'.$op['operation_name'].'</td>
            <td>'.$op['produced_quantity'].'</td>
            <td>'.$op['ok_quantity'].'</td>
            <td>'.$op['accepted_quantity'].'</td>
            <td>'.$op['rework_quantity'].'</td>
            <td>'.$op['rejected_quantity'].'</td>
            <td>'.$op['remark'].'</td>
            <td>'.$op['checked_by'].'</td>
        </tr>';
        
        $row_count++;
        
        // Check if we need a new page (leaving 30mm at bottom)
        if ($pdf->GetY() > 160 && $row_count < $ops_result->num_rows) {
            $html .= '</table>';
            $pdf->writeHTML($html, true, false, true, false, '');
            
            // Add new page
            $pdf->AddPage();
            
            // Add operations header on new page
            $pdf->SetFont('helvetica', 'B', 12);
            $pdf->SetFillColor($headerColor2[0], $headerColor2[1], $headerColor2[2]);
            $pdf->SetTextColor(255, 255, 255);
            $pdf->Cell(0, 8, 'OPERATIONS DETAILS (CONTINUED)', 0, 1, 'C', true);
            $pdf->SetTextColor(0, 0, 0);
            
            // Start new table with header
            $html = '<table class="ops-table">
                <tr>
                    <th width="10%">Date</th>
                    <th width="6%">Op No</th>
                    <th width="18%">Operation</th>
                    <th width="9%">Produced</th>
                    <th width="9%">OK</th>
                    <th width="9%">Accepted</th>
                    <th width="9%">Rework</th>
                    <th width="9%">Rejected</th>
                    <th width="15%">Remark</th>
                    <th width="6%">Checked By</th>
                </tr>';
        }
    }
    
    $html .= '</table>';
    $pdf->writeHTML($html, true, false, true, false, '');
} else {
    $pdf->SetFont('helvetica', '', 12);
    $pdf->Cell(0, 10, 'No operations found for this job', 0, 1, 'C');
}

// Output PDF
$pdf->Output('job_card_'.$order_id.'_report.pdf', 'D');